### PR TITLE
add brid.gy emoji example

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by pfefferle** [comment]
to be able to test this problem https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/71

**Comment by voxpelli** [comment]
I'm :+1: on this, maybe I can add you @pfefferle as a co-maintainer so we can help each other in pushing new versions? I'll keep this PR open until I have time to merge it and release a new version otherwise :)

**Comment by pfefferle** [comment]
@voxpelli oh thanks, I help where I can ;)

**Comment by pfefferle** [comment]
@voxpelli ping ping :)

**Comment by pfefferle** [comment]
thanks and thanks for adding me as contributor!

**Comment by voxpelli** [comment]
@pfefferle I'm adding your npm user, https://www.npmjs.com/~pfefferle, as an owner of the npm package as well – then I will go ahead and make an actual release of this myself :)

**Comment by voxpelli** [comment]
@pfefferle Published as `0.6.1`

**Pull request merged**
